version: '3.5'

services:
  ms-relatorios:
    container_name: ms-mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=e296cd9f
