version: '3.5'

services:
  ms-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456

  ms-consul:
    container_name: consul
    image: consul
    ports:
      - "8500:8500"