version: '3.5'

services:
  ms-redis:
    image: redis
    ports:
      - "6379:6379"

  ms-zookeeper:
    container_name: zookeeper
    image: jplock/zookeeper
    ports:
      - "2181:2181"

  ms-kafka:
    container_name: kafka
    image: ches/kafka
    ports:
      - "7203:7203"
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=172.24.176.1
      - ZOOKEEPER_IP=172.24.176.1

  ms-kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8888:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=172.24.176.1:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=172.0.0.1:2181