micronaut:
  application:
    name: relatorioService
  server:
    port: -1

kafka:
  bootstrap:
    servers: kafka:9092

mongodb:
  uri: 'mongodb://root:e296cd9f@ms-mongo:27017/vendas'

consul:
  client:
    registration:
      enabled: true
    default-zone: "consul:8500"